/* Crop2Value app: translations (D), data, views, voice, and home-page extras */
const LI=['en','hi','mr','ml','ta'],N={en:'English',hi:'हिन्दी',mr:'मराठी',ml:'മലയാളം',ta:'தமிழ்'},LC={en:'en-IN',hi:'hi-IN',mr:'mr-IN',ml:'ml-IN',ta:'ta-IN'};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),L=k=>{try{return JSON.parse(localStorage.getItem(k))}catch(e){return null}};
/* i18n: key:[en,hi,mr,ml,ta]. Add a language by adding a column + LI/N/LC entries. */
const D={
tag:['Turn Agricultural Waste Into Rural Wealth','कृषि कचरे को ग्रामीण संपत्ति में बदलें','शेतीतील कचऱ्याचे ग्रामीण संपत्तीत रूपांतर करा','കാർഷിക മാലിന്യത്തെ ഗ്രാമീണ സമ്പത്താക്കൂ','விவசாயக் கழிவை கிராமப்புற செல்வமாக மாற்றுங்கள்'],
sub:['Sell crop residue. Find buyers. Rent equipment.','फसल अवशेष बेचें। खरीदार खोजें। उपकरण किराए पर लें।','पीक अवशेष विका. खरेदीदार शोधा. उपकरणे भाड्याने घ्या.','വിള അവശിഷ്ടങ്ങൾ വിൽക്കൂ. വാങ്ങുന്നവരെ കണ്ടെത്തൂ. ഉപകരണങ്ങൾ വാടകയ്ക്ക് എടുക്കൂ.','பயிர் எச்சங்களை விற்கவும். வாங்குபவர்களைக் கண்டறியவும். உபகரணங்களை வாடகைக்கு எடுக்கவும்.'],
home:['Home','होम','मुख्यपृष्ठ','ഹോം','முகப்பு'],market:['Marketplace','बाज़ार','बाजार','വിപണി','சந்தை'],sell:['Sell / List','बेचें / लिस्ट करें','विका / लिस्ट करा','വിൽക്കുക / ലിസ്റ്റ്','விற்க / பட்டியலிட'],rent:['Rent Equipment','उपकरण किराए पर','उपकरण भाड्याने','ഉപകരണം വാടകയ്ക്ക്','உபகரண வாடகை'],reqs:['Requests','मांग','मागण्या','ആവശ്യങ്ങൾ','கோரிக்கைகள்'],gov:['Govt Schemes','सरकारी योजनाएं','सरकारी योजना','സർക്കാർ പദ്ധതികൾ','அரசு திட்டங்கள்'],msgs:['Messages','संदेश','संदेश','സന്ദേശങ്ങൾ','செய்திகள்'],map:['Map','नक्शा','नकाशा','മാപ്പ്','வரைபடம்'],hist:['History','इतिहास','इतिहास','ചരിത്രം','வரலாறு'],impact:['Impact','प्रभाव','प्रभाव','സ്വാധീനം','தாக்கம்'],
login:['Login / Sign up','लॉगिन / साइन अप','लॉगिन / साइन अप','ലോഗിൻ / സൈൻ അപ്പ്','உள்நுழை / பதிவு'],logout:['Logout','लॉग आउट','लॉग आउट','ലോഗ് ഔട്ട്','வெளியேறு'],find:['Find Buyers','खरीदार खोजें','खरेदीदार शोधा','വാങ്ങുന്നവരെ കണ്ടെത്തുക','வாங்குபவர்களைக் காண்க'],ask:['Ask Crop2Value','Crop2Value से पूछें','Crop2Value ला विचारा','Crop2Value-നോട് ചോദിക്കൂ','Crop2Value-ஐ கேளுங்கள்'],
ph:['What are you looking for?','आप क्या खोज रहे हैं?','तुम्ही काय शोधत आहात?','നിങ്ങൾ എന്താണ് തിരയുന്നത്?','என்ன தேடுகிறீர்கள்?'],go:['Search','खोजें','शोधा','തിരയുക','தேடு'],feat:['Featured','विशेष','निवडक','തിരഞ്ഞെടുത്തവ','சிறப்பு'],dm:['Demo','डेमो','डेमो','ഡെമോ','டெமோ'],ind:['Indicative, not guaranteed','सांकेतिक, गारंटी नहीं','सूचक, हमी नाही','സൂചന മാത്രം, ഉറപ്പില്ല','தோராயம், உறுதி இல்லை'],
c1:['Crop Residue','फसल अवशेष','पीक अवशेष','വിള അവശിഷ്ടം','பயிர் எச்சம்'],c2:['By-products','उप-उत्पाद','उप-उत्पादने','ഉപോൽപ്പന്നങ്ങൾ','துணைப் பொருட்கள்'],c3:['Equipment','उपकरण','उपकरणे','ഉപകരണങ്ങൾ','உபகரணங்கள்'],c4:['Services','सेवाएँ','सेवा','സേവനങ്ങൾ','சேவைகள்'],c5:['Processed Products','प्रसंस्कृत उत्पाद','प्रक्रिया केलेली उत्पादने','സംസ്കരിച്ച ഉൽപ്പന്നങ്ങൾ','பதப்படுத்திய பொருட்கள்'],
all:['All','सभी','सर्व','എല്ലാം','அனைத்தும்'],new:['Newest','नवीनतम','नवीन','പുതിയത്','புதியவை'],nrst:['Nearest','सबसे पास','सर्वात जवळ','ഏറ്റവും അടുത്ത്','அருகில்'],low:['Lowest price','कम कीमत','कमी किंमत','കുറഞ്ഞ വില','குறைந்த விலை'],high:['Highest price','अधिक कीमत','जास्त किंमत','കൂടിയ വില','அதிக விலை'],clr:['Clear filters','फ़िल्टर हटाएं','फिल्टर काढा','ഫിൽട്ടർ മായ്ക്കുക','வடிகட்டி நீக்கு'],none:['Nothing here yet','यहाँ अभी कुछ नहीं','इथे अजून काही नाही','ഇവിടെ ഒന്നുമില്ല','இங்கு எதுவும் இல்லை'],tsell:['For sale','बिक्री के लिए','विक्रीसाठी','വിൽപ്പനയ്ക്ക്','விற்பனைக்கு'],ver:['Verified','सत्यापित','सत्यापित','സ്ഥിരീകരിച്ചത്','சரிபார்க்கப்பட்டது'],apx:['Approx.','लगभग','अंदाजे','ഏകദേശം','தோராயமாக'],
offer:['Make Offer','ऑफर दें','ऑफर द्या','ഓഫർ നൽകുക','விலை முன்மொழி'],qty:['Quantity','मात्रा','प्रमाण','അളവ്','அளவு'],price:['Price','कीमत','किंमत','വില','விலை'],chat:['Chat','चैट','चॅट','ചാറ്റ്','அரட்டை'],save:['Save','सेव','सेव्ह','സേവ്','சேமி'],priv:['Only approximate location is shown. Exact location is shared after confirmation.','केवल अनुमानित स्थान दिखता है। सटीक स्थान पुष्टि के बाद।','फक्त अंदाजे ठिकाण दिसते. अचूक ठिकाण पुष्टीनंतर.','ഏകദേശ സ്ഥലം മാത്രം. കൃത്യമായ സ്ഥലം സ്ഥിരീകരണത്തിന് ശേഷം.','தோராயமான இடம் மட்டும். சரியான இடம் உறுதிக்குப் பின்.'],match:['Smart matches','स्मार्ट मैच','स्मार्ट मॅच','സ്മാർട്ട് മാച്ച്','ஸ்மார்ட் பொருத்தம்'],mt:['match','मैच','मॅच','മാച്ച്','பொருத்தம்'],
call:['Call','कॉल','कॉल','വിളിക്കുക','அழை'],clock:['Calling opens once your order or booking is accepted','ऑर्डर या बुकिंग स्वीकार होने पर कॉल खुलेगा','ऑर्डर किंवा बुकिंग स्वीकारल्यावर कॉल सुरू होईल','ഓർഡറോ ബുക്കിംഗോ സ്വീകരിച്ചാൽ വിളിക്കാം','ஆர்டர் அல்லது முன்பதிவு ஏற்கப்பட்டதும் அழைக்கலாம்'],clog:['Please log in first','पहले लॉगिन करें','आधी लॉगिन करा','ആദ്യം ലോഗിൻ ചെയ്യുക','முதலில் உள்நுழையவும்'],cnow:['Call now','अभी कॉल करें','आता कॉल करा','ഇപ്പോൾ വിളിക്കുക','இப்போது அழை'],cancel:['Cancel','रद्द करें','रद्द करा','റദ്ദാക്കുക','ரத்து'],
thx:['Thanks! Pickup this week works for me.','धन्यवाद! इस हफ्ते पिकअप ठीक है।','धन्यवाद! या आठवड्यात पिकअप चालेल.','നന്ദി! ഈ ആഴ്ച പിക്കപ്പ് ശരിയാണ്.','நன்றி! இந்த வாரம் பிக்கப் சரி.'],offm:['Offer','ऑफर','ऑफर','ഓഫർ','விலை'],ctr:['Counter offer','काउंटर ऑफर','काउंटर ऑफर','കൗണ്ടർ ഓഫർ','எதிர் விலை'],acc:['Accept','स्वीकार','स्वीकारा','സ്വീകരിക്കുക','ஏற்கவும்'],accd:['Accepted, deal confirmed at','स्वीकार, सौदा पक्का','स्वीकारले, व्यवहार निश्चित','സ്വീകരിച്ചു, ഇടപാട് ഉറപ്പായി','ஏற்கப்பட்டது, ஒப்பந்தம் உறுதி'],onl:['online','ऑनलाइन','ऑनलाइन','ഓൺലൈൻ','ஆன்லைன்'],
mybk:['My bookings','मेरी बुकिंग','माझ्या बुकिंग','എന്റെ ബുക്കിംഗുകൾ','என் முன்பதிவுகள்'],book:['Request booking','बुकिंग अनुरोध','बुकिंग विनंती','ബുക്കിംഗ് അഭ്യർത്ഥന','முன்பதிவு கோரிக்கை'],from:['From','से','पासून','മുതൽ','இருந்து'],to:['To','तक','पर्यंत','വരെ','வரை'],dep:['Deposit','जमा राशि','ठेव','നിക്ഷേപം','வைப்புத்தொகை'],b0:['Requested','अनुरोध भेजा','विनंती केली','അഭ്യർത്ഥിച്ചു','கோரப்பட்டது'],b1:['Accepted','स्वीकृत','स्वीकारले','സ്വീകരിച്ചു','ஏற்கப்பட்டது'],b2:['Payment pending','भुगतान बाकी','पेमेंट बाकी','പേയ്മെന്റ് ബാക്കി','கட்டணம் நிலுவை'],b3:['Confirmed','पक्का','निश्चित','സ്ഥിരീകരിച്ചു','உறுதி'],pay:['Pay (demo)','भुगतान (डेमो)','पेमेंट (डेमो)','പേയ്മെന്റ് (ഡെമോ)','செலுத்து (டெமோ)'],nav:['Not available on those dates','उन तारीखों पर उपलब्ध नहीं','त्या तारखांना उपलब्ध नाही','ആ തീയതികളിൽ ലഭ്യമല്ല','அந்த தேதிகளில் இல்லை'],dte:['End date must be after start date','अंतिम तारीख शुरुआत के बाद हो','शेवटची तारीख सुरुवातीनंतर हवी','അവസാന തീയതി ശേഷം ആയിരിക്കണം','முடிவு தேதி தொடக்கத்துக்குப் பின் இருக்க வேண்டும்'],
w1:['What are you listing?','आप क्या लिस्ट कर रहे हैं?','तुम्ही काय लिस्ट करत आहात?','എന്താണ് ലിസ്റ്റ് ചെയ്യുന്നത്?','எதைப் பட்டியலிடுகிறீர்கள்?'],cat:['Category','श्रेणी','वर्ग','വിഭാഗം','வகை'],det:['Details','विवरण','तपशील','വിവരങ്ങൾ','விவரங்கள்'],loc:['Location','स्थान','ठिकाण','സ്ഥലം','இடம்'],photo:['Photo','फोटो','फोटो','ഫോട്ടോ','புகைப்படம்'],prev:['Preview','पूर्वावलोकन','पूर्वदर्शन','പ്രിവ്യൂ','முன்னோட்டம்'],mat:['Material','सामग्री','साहित्य','വസ്തു','பொருள்'],ttl:['Title (optional)','शीर्षक (वैकल्पिक)','शीर्षक (ऐच्छिक)','തലക്കെട്ട് (ഓപ്ഷണൽ)','தலைப்பு (விருப்பம்)'],unit:['Unit','इकाई','एकक','യൂണിറ്റ്','அலகு'],neg:['Negotiable','मोलभाव संभव','वाटाघाटी शक्य','വിലപേശാം','பேரம் பேசலாம்'],pin:['Pincode','पिनकोड','पिनकोड','പിൻകോഡ്','அஞ்சல் குறியீடு'],locph:['Village / City, District','गांव / शहर, जिला','गाव / शहर, जिल्हा','ഗ്രാമം / നഗരം, ജില്ല','கிராமம் / நகரம், மாவட்டம்'],back:['Back','पीछे','मागे','പിന്നോട്ട്','பின்'],next:['Next','आगे','पुढे','അടുത്തത്','அடுத்து'],pub:['Publish','प्रकाशित करें','प्रकाशित करा','പ്രസിദ്ധീകരിക്കുക','வெளியிடு'],e_det:['Add quantity and price','मात्रा और कीमत भरें','प्रमाण आणि किंमत भरा','അളവും വിലയും ചേർക്കുക','அளவு, விலை சேர்க்கவும்'],e_loc:['Add your location','अपना स्थान भरें','ठिकाण भरा','സ്ഥലം ചേർക്കുക','இடத்தைச் சேர்க்கவும்'],rqt:['Request','मांग','मागणी','ആവശ്യം','கோரிக்கை'],
buy:['Buy','खरीद','खरेदी','വാങ്ങൽ','வாங்க'],rentt:['Rent','किराया','भाडे','വാടക','வாடகை'],need:['Needed','चाहिए','हवे','ആവശ്യമുണ്ട്','தேவை'],have:['Available','उपलब्ध','उपलब्ध','ലഭ്യമാണ്','கிடைக்கும்'],km:['km','कि.मी.','कि.मी.','കി.മീ','கி.மீ'],supply:['I can supply','मैं आपूर्ति कर सकता हूँ','मी पुरवू शकतो','എനിക്ക് നൽകാം','நான் வழங்க முடியும்'],provide:['I can provide','मैं उपलब्ध करा सकता हूँ','मी उपलब्ध करून देऊ शकतो','എനിക്ക് നൽകാൻ കഴിയും','நான் வழங்க இயலும்'],resp:['Responded','जवाब दिया','प्रतिसाद दिला','പ്രതികരിച്ചു','பதிலளித்தது'],agg:['Aggregation','एकत्रीकरण','एकत्रीकरण','സമാഹരണം','ஒருங்கிணைப்பு'],logi:['Est. logistics','अनुमानित ढुलाई','अंदाजे वाहतूक','ഏകദേശ ലോജിസ്റ്റിക്സ്','மதிப்பிட்ட போக்குவரத்து'],mk:['Create batch','बैच बनाएं','बॅच तयार करा','ബാച്ച് സൃഷ്ടിക്കുക','தொகுதி உருவாக்கு'],nxt:['Next status','अगली स्थिति','पुढील स्थिती','അടുത്ത നില','அடுத்த நிலை'],bs0:['Open','खुला','खुला','തുറന്നത്','திறந்தது'],bs1:['Collecting','संग्रह जारी','संकलन सुरू','ശേഖരിക്കുന്നു','சேகரிப்பு'],bs2:['Ready','तैयार','तयार','തയ്യാർ','தயார்'],bs3:['Pickup scheduled','पिकअप तय','पिकअप ठरले','പിക്കപ്പ് നിശ്ചയിച്ചു','பிக்கப் திட்டமிடப்பட்டது'],bs4:['Delivered','पहुंचाया','पोहोचवले','എത്തിച്ചു','வழங்கப்பட்டது'],bs5:['Completed','पूर्ण','पूर्ण','പൂർത്തിയായി','முடிந்தது'],showall:['Show all','सभी दिखाएं','सर्व दाखवा','എല്ലാം കാണിക്കുക','அனைத்தும் காட்டு'],post:['Post a request','मांग डालें','मागणी टाका','ആവശ്യം പോസ്റ്റ് ചെയ്യുക','கோரிக்கை இடு'],
i_res:['Residue listed','सूचीबद्ध अवशेष','सूचीबद्ध अवशेष','ലിസ്റ്റ് ചെയ്ത അവശിഷ്ടം','பட்டியலிட்ட எச்சம்'],i_div:['Est. diverted from waste','अनुमानित कचरे से बचा','अंदाजे कचऱ्यापासून वाचवले','ഏകദേശം മാലിന്യത്തിൽ നിന്ന് ഒഴിവാക്കി','மதிப்பிட்ட கழிவு தவிர்ப்பு'],i_far:['Farmers connected','जुड़े किसान','जोडलेले शेतकरी','ബന്ധിപ്പിച്ച കർഷകർ','இணைந்த விவசாயிகள்'],i_buy:['Buyers connected','जुड़े खरीदार','जोडलेले खरेदीदार','ബന്ധിപ്പിച്ച വാങ്ങുന്നവർ','இணைந்த வாங்குபவர்கள்'],i_rent:['Rentals requested','किराए के अनुरोध','भाड्याच्या विनंत्या','വാടക അഭ്യർത്ഥനകൾ','வாடகை கோரிக்கைகள்'],i_deal:['Confirmed deals','पक्के सौदे','निश्चित व्यवहार','ഉറപ്പായ ഇടപാടുകൾ','உறுதி ஒப்பந்தங்கள்'],i_chart:['Monthly listed volume','मासिक सूचीबद्ध मात्रा','मासिक सूचीबद्ध प्रमाण','പ്രതിമാസ ലിസ്റ്റ് അളവ്','மாதாந்திர பட்டியல் அளவு'],
mob:['Mobile number','मोबाइल नंबर','मोबाइल नंबर','മൊബൈൽ നമ്പർ','மொபைல் எண்'],name:['Name','नाम','नाव','പേര്','பெயர்'],email:['Email','ईमेल','ईमेल','ഇമെയിൽ','மின்னஞ்சல்'],state:['State','राज्य','राज्य','സംസ്ഥാനം','மாநிலம்'],vil:['Village / City','गांव / शहर','गाव / शहर','ഗ്രാമം / നഗരം','கிராமம் / நகரம்'],pw:['Password','पासवर्ड','पासवर्ड','പാസ്‌വേഡ്','கடவுச்சொல்'],iam:['I am a','मैं हूँ','मी आहे','ഞാൻ ഒരു','நான் ஒரு'],r_farmer:['Farmer','किसान','शेतकरी','കർഷകൻ','விவசாயி'],r_buyer:['Buyer','खरीदार','खरेदीदार','വാങ്ങുന്നയാൾ','வாங்குபவர்'],r_renter:['Renter','किराएदार','भाडेकरू','വാടകക്കാരൻ','வாடகைதாரர்'],r_service:['Service provider','सेवा प्रदाता','सेवा पुरवठादार','സേവന ദാതാവ്','சேவை வழங்குநர்'],r_business:['Business','व्यवसाय','व्यवसाय','ബിസിനസ്','வணிகம்'],sotp:['Send OTP →','OTP भेजें →','OTP पाठवा →','OTP അയയ്ക്കുക →','OTP அனுப்பு →'],vh:['Verify your number','अपना नंबर सत्यापित करें','तुमचा नंबर सत्यापित करा','നിങ്ങളുടെ നമ്പർ സ്ഥിരീകരിക്കുക','உங்கள் எண்ணைச் சரிபார்க்கவும்'],code:['6-digit code','6 अंकों का कोड','6 अंकी कोड','6 അക്ക കോഡ്','6 இலக்க குறியீடு'],vf:['Verify','सत्यापित करें','सत्यापित करा','സ്ഥിരീകരിക്കുക','சரிபார்'],rsd:['Resend','दोबारा भेजें','पुन्हा पाठवा','വീണ്ടും അയയ്ക്കുക','மீண்டும் அனுப்பு'],wr:['Wrong code, try again','गलत कोड, फिर कोशिश करें','चुकीचा कोड, पुन्हा प्रयत्न करा','തെറ്റായ കോഡ്, വീണ്ടും ശ്രമിക്കുക','தவறான குறியீடு, மீண்டும் முயற்சிக்கவும்'],im:['Invalid mobile number','अमान्य मोबाइल नंबर','अवैध मोबाइल नंबर','തെറ്റായ മൊബൈൽ നമ്പർ','தவறான மொபைல் எண்'],pv:['Phone verified','फोन सत्यापित','फोन सत्यापित','ഫോൺ സ്ഥിരീകരിച്ചു','தொலைபேசி சரிபார்க்கப்பட்டது'],npv:['Phone not verified','फोन सत्यापित नहीं','फोन सत्यापित नाही','ഫോൺ സ്ഥിരീകരിച്ചിട്ടില്ല','தொலைபேசி சரிபார்க்கப்படவில்லை'],
st0:['Maharashtra','महाराष्ट्र','महाराष्ट्र','മഹാരാഷ്ട്ര','மகாராஷ்டிரா'],st1:['Kerala','केरल','केरळ','കേരളം','கேரளா'],st2:['Tamil Nadu','तमिलनाडु','तामिळनाडू','തമിഴ്നാട്','தமிழ்நாடு'],st3:['Punjab','पंजाब','पंजाब','പഞ്ചാബ്','பஞ்சாப்'],st4:['Haryana','हरियाणा','हरियाणा','ഹരിയാന','ஹரியானா'],st5:['Uttar Pradesh','उत्तर प्रदेश','उत्तर प्रदेश','ഉത്തർപ്രദേശ്','உத்தரப் பிரதேசம்'],st6:['Other','अन्य','इतर','മറ്റുള്ളവ','மற்றவை'],
p_kamptee:['Kamptee','कामठी','कामठी','കാംപ്റ്റി','காம்ப்டி'],p_nagpur:['Nagpur','नागपुर','नागपूर','നാഗ്പൂർ','நாக்பூர்'],p_umred:['Umred','उमरेड','उमरेड','ഉമ്രെഡ്','உம்ரெட்'],p_hingna:['Hingna','हिंगना','हिंगणा','ഹിംഗ്ന','ஹிங்கனா'],p_wardha:['Wardha','वर्धा','वर्धा','വാർധ','வார்தா'],p_kochi:['Kochi','कोच्चि','कोची','കൊച്ചി','கொச்சி'],p_katol:['Katol','कटोल','काटोल','കടോൾ','கட்டோல்'],
m_rice:['Rice straw','धान की पराली','तांदळाचा काडा','നെല്ല് വൈക്കോൽ','நெல் வைக்கோல்'],m_wheat:['Wheat straw','गेहूं का भूसा','गव्हाचा भुसा','ഗോതമ്പ് വൈക്കോൽ','கோதுமை வைக்கோல்'],m_cotton:['Cotton stalk','कपास डंठल','कापूस काड्या','പരുത്തി തണ്ട്','பருத்தி தண்டு'],m_coconut:['Coconut husk','नारियल की भूसी','नारळाच्या शेंड्या','തേങ്ങാ തൊണ്ട്','தேங்காய் நார்'],m_tractor:['Mahindra Tractor','महिंद्रा ट्रैक्टर','महिंद्रा ट्रॅक्टर','മഹീന്ദ്ര ട്രാക്ടർ','மஹிந்திரா டிராக்டர்'],m_rotav:['Rotavator','रोटावेटर','रोटाव्हेटर','റോട്ടവേറ്റർ','ரோட்டவேட்டர்'],m_harv:['Harvesting service','कटाई सेवा','कापणी सेवा','വിളവെടുപ്പ് സേവനം','அறுவடை சேவை'],m_comp:['Compost','कम्पोस्ट खाद','कंपोस्ट खत','കമ്പോസ്റ്റ്','உரம்'],
u_t:['ton','टन','टन','ടൺ','டன்'],u_kg:['kg','किग्रा','किलो','കിലോ','கிலோ'],u_day:['day','दिन','दिवस','ദിവസം','நாள்'],u_acre:['acre','एकड़','एकर','ഏക്കർ','ஏக்கர்'],
elig:['Check eligibility','पात्रता जांचें','पात्रता तपासा','യോഗ്യത പരിശോധിക്കുക','தகுதி சரிபார்'],land:['Land (acres)','ज़मीन (एकड़)','जमीन (एकर)','ഭൂമി (ഏക്കർ)','நிலம் (ஏக்கர்)'],what:['What do you want to do?','आप क्या करना चाहते हैं?','तुम्हाला काय करायचे आहे?','നിങ്ങൾ എന്ത് ചെയ്യാൻ ആഗ്രഹിക്കുന്നു?','நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?'],a1:['Manage crop residue','फसल अवशेष प्रबंधन','पीक अवशेष व्यवस्थापन','വിള അവശിഷ്ട പരിപാലനം','பயிர் எச்ச மேலாண்மை'],a2:['Buy machinery','मशीनरी खरीदें','यंत्रसामग्री खरेदी','യന്ത്രം വാങ്ങുക','இயந்திரம் வாங்க'],a3:['Irrigation pump','सिंचाई पंप','सिंचन पंप','ജലസേചന പമ്പ്','பாசன பம்பு'],a4:['Biomass / collection unit','बायोमास / संग्रह इकाई','बायोमास / संकलन युनिट','ബയോമാസ് / ശേഖരണ യൂണിറ്റ്','உயிர்ம / சேகரிப்பு அலகு'],sug:['scheme(s) may suit you','योजना आपके लिए उपयुक्त हो सकती हैं','योजना तुम्हाला उपयुक्त असू शकतात','പദ്ധതികൾ നിങ്ങൾക്ക് അനുയോജ്യമായേക്കാം','திட்டங்கள் உங்களுக்குப் பொருந்தலாம்'],nom:['No match yet. Try other activities or land size.','अभी कोई मेल नहीं। अन्य गतिविधि या ज़मीन आज़माएं।','अजून जुळणी नाही. इतर कृती किंवा जमीन वापरून पहा.','പൊരുത്തമില്ല. മറ്റ് പ്രവർത്തനം/ഭൂമി പരീക്ഷിക്കുക.','பொருத்தம் இல்லை. வேறு செயல்/நிலம் முயற்சிக்கவும்.'],actv:['Active campaigns','सक्रिय अभियान','सक्रिय मोहिमा','സജീവ കാമ്പെയ്നുകൾ','செயலில் உள்ள பிரச்சாரங்கள்'],mayel:['You may be eligible','आप पात्र हो सकते हैं','तुम्ही पात्र असू शकता','നിങ്ങൾ യോഗ്യരായേക്കാം','நீங்கள் தகுதி பெறலாம்'],apply:['Apply on official website ↗','आधिकारिक वेबसाइट पर आवेदन ↗','अधिकृत वेबसाइटवर अर्ज करा ↗','ഔദ്യോഗിക വെബ്സൈറ്റിൽ അപേക്ഷിക്കുക ↗','அதிகாரப்பூர்வ இணையதளத்தில் விண்ணப்பிக்க ↗'],cen:['Central Government','केंद्र सरकार','केंद्र सरकार','കേന്ദ്ര സർക്കാർ','மத்திய அரசு'],sta:['State Government','राज्य सरकार','राज्य सरकार','സംസ്ഥാന സർക്കാർ','மாநில அரசு'],gnote:['Campaigns are published by government admins through the backend, not from this site. Criteria are indicative: confirm on the official portal.','अभियान सरकारी प्रशासक बैकएंड से प्रकाशित करते हैं, इस साइट से नहीं। मानदंड सांकेतिक हैं: आधिकारिक पोर्टल पर जांचें।','मोहिमा सरकारी प्रशासक बॅकएंडवरून प्रकाशित करतात, या साइटवरून नाही. निकष सूचक आहेत: अधिकृत पोर्टलवर तपासा.','കാമ്പെയ്നുകൾ സർക്കാർ അഡ്മിൻമാർ ബാക്കെൻഡ് വഴി പ്രസിദ്ധീകരിക്കുന്നു, ഈ സൈറ്റിൽ നിന്നല്ല. മാനദണ്ഡങ്ങൾ സൂചന മാത്രം: ഔദ്യോഗിക പോർട്ടലിൽ പരിശോധിക്കുക.','பிரச்சாரங்களை அரசு நிர்வாகிகள் பின்தளம் வழியாக வெளியிடுகிறார்கள், இந்தத் தளத்திலிருந்து அல்ல. அளவுகோல்கள் தோராயம்: அதிகாரப்பூர்வ தளத்தில் சரிபார்க்கவும்.'],
g1b:['₹6,000 per year income support','₹6,000 प्रति वर्ष आय सहायता','₹6,000 प्रति वर्ष उत्पन्न सहाय्य','പ്രതിവർഷം ₹6,000 വരുമാന സഹായം','ஆண்டுக்கு ₹6,000 வருமான உதவி'],g2b:['Up to 50% subsidy on residue machines','अवशेष मशीनों पर 50% तक सब्सिडी','अवशेष यंत्रांवर 50% पर्यंत अनुदान','അവശിഷ്ട യന്ത്രങ്ങൾക്ക് 50% വരെ സബ്സിഡി','எச்ச இயந்திரங்களுக்கு 50% வரை மானியம்'],g3b:['Machinery subsidy, usually 40–50%','मशीनरी सब्सिडी, आमतौर पर 40–50%','यंत्रसामग्री अनुदान, साधारण 40–50%','യന്ത്ര സബ്സിഡി, സാധാരണ 40–50%','இயந்திர மானியம், பொதுவாக 40–50%'],g4b:['Central + state subsidy on solar pumps','सोलर पंप पर केंद्र + राज्य सब्सिडी','सोलर पंपावर केंद्र + राज्य अनुदान','സോളാർ പമ്പിന് കേന്ദ്ര + സംസ്ഥാന സബ്സിഡി','சோலார் பம்புக்கு மத்திய + மாநில மானியம்'],g5b:['Support for biogas / bio-CNG units','बायोगैस / बायो-CNG इकाइयों को सहायता','बायोगॅस / बायो-CNG युनिटसाठी मदत','ബയോഗ്യാസ് / ബയോ-CNG യൂണിറ്റുകൾക്ക് സഹായം','பயோகேஸ் / பயோ-CNG அலகுகளுக்கு உதவி'],g6b:['Loans up to ₹2 crore, 3% interest subvention','₹2 करोड़ तक ऋण, 3% ब्याज छूट','₹2 कोटी पर्यंत कर्ज, 3% व्याज सवलत','₹2 കോടി വരെ വായ്പ, 3% പലിശ ഇളവ്','₹2 கோடி வரை கடன், 3% வட்டி மானியம்'],g7b:['Buyer linkage + free collection days','खरीदार जुड़ाव + मुफ्त संग्रह दिवस','खरेदीदार जोडणी + मोफत संकलन दिवस','വാങ്ങുന്നവരുമായി ബന്ധം + സൗജന്യ ശേഖരണ ദിനം','வாங்குபவர் இணைப்பு + இலவச சேகரிப்பு நாட்கள்'],
mapn:['Approximate locations only, for privacy.','गोपनीयता के लिए केवल अनुमानित स्थान।','गोपनीयतेसाठी फक्त अंदाजे ठिकाणे.','സ്വകാര്യതയ്ക്കായി ഏകദേശ സ്ഥലങ്ങൾ മാത്രം.','தனியுரிமைக்காக தோராயமான இடங்கள் மட்டும்.'],you:['You','आप','तुम्ही','നിങ്ങൾ','நீங்கள்'],f_b:['Buyers','खरीदार','खरेदीदार','വാങ്ങുന്നവർ','வாங்குபவர்கள்'],f_s:['Sellers','विक्रेता','विक्रेते','വിൽപ്പനക്കാർ','விற்பனையாளர்கள்'],cc:['Collection centre','संग्रह केंद्र','संकलन केंद्र','ശേഖരണ കേന്ദ്രം','சேகரிப்பு மையம்'],open:['Open','खोलें','उघडा','തുറക്കുക','திற'],w_bio:['Biomass Buyer','बायोमास खरीदार','बायोमास खरेदीदार','ബയോമാസ് വാങ്ങുന്നയാൾ','உயிர்ம வாங்குபவர்'],w_comp:['Compost Processor','कम्पोस्ट प्रोसेसर','कंपोस्ट प्रोसेसर','കമ്പോസ്റ്റ് പ്രോസസർ','உரம் பதப்படுத்துநர்'],w_bri:['Briquette Unit','ब्रिकेट इकाई','ब्रिकेट युनिट','ബ്രിക്കറ്റ് യൂണിറ്റ്','பிரிக்கெட் அலகு'],w_far:['Demo Farmer','डेमो किसान','डेमो शेतकरी','ഡെമോ കർഷകൻ','டெமோ விவசாயி'],o_kis:['Kisan Equip Co.','किसान इक्विप कं.','किसान इक्विप कं.','കിസാൻ ഇക്വിപ് കമ്പനി','கிசான் எக்விப் நிறுவனம்'],o_agr:['Agro Services','एग्रो सर्विसेज','अ‍ॅग्रो सर्व्हिसेस','അഗ്രോ സർവീസസ്','அக்ரோ சர்வீசஸ்'],o_grn:['Green Compost Unit','ग्रीन कम्पोस्ट इकाई','ग्रीन कंपोस्ट युनिट','ഗ്രീൻ കമ്പോസ്റ്റ് യൂണിറ്റ്','கிரீன் உரம் அலகு'],
e_off:['Offer sent','ऑफर भेजा','ऑफर पाठवला','ഓഫർ അയച്ചു','விலை அனுப்பப்பட்டது'],e_ctr:['Counter offer from','काउंटर ऑफर:','काउंटर ऑफर:','കൗണ്ടർ ഓഫർ:','எதிர் விலை:'],e_ok:['Deal confirmed','सौदा पक्का','व्यवहार निश्चित','ഇടപാട് ഉറപ്പായി','ஒப்பந்தம் உறுதி'],e_bk:['Booking requested','बुकिंग अनुरोध','बुकिंग विनंती','ബുക്കിംഗ് അഭ്യർത്ഥന','முன்பதிவு கோரிக்கை'],e_bka:['Booking accepted by','बुकिंग स्वीकृत:','बुकिंग स्वीकारली:','ബുക്കിംഗ് സ്വീകരിച്ചു:','முன்பதிவு ஏற்பு:'],e_pub:['Published','प्रकाशित','प्रकाशित','പ്രസിദ്ധീകരിച്ചു','வெளியிடப்பட்டது'],e_app:['Opened application portal for','आवेदन पोर्टल खोला:','अर्ज पोर्टल उघडले:','അപേക്ഷാ പോർട്ടൽ തുറന്നു:','விண்ணப்ப தளம் திறக்கப்பட்டது:'],e_call:['Called','कॉल किया','कॉल केला','വിളിച്ചു','அழைத்தார்'],e_msg:['New message from','नया संदेश:','नवीन संदेश:','പുതിയ സന്ദേശം:','புதிய செய்தி:'],e_ver:['Number verified','नंबर सत्यापित','नंबर सत्यापित','നമ്പർ സ്ഥിരീകരിച്ചു','எண் சரிபார்க்கப்பட்டது'],e_vo:['Voice command','वॉइस कमांड','व्हॉइस कमांड','വോയ്സ് കമാൻഡ്','குரல் கட்டளை'],
try:['Try: “Find rice straw buyers near me”','कहें: “मेरे पास के धान की पराली के खरीदार दिखाओ”','म्हणा: “माझ्या जवळचे तांदळाच्या काडाचे खरेदीदार दाखवा”','പറയൂ: “എന്റെ അടുത്തുള്ള വാങ്ങുന്നവരെ കാണിക്കുക”','சொல்லுங்கள்: “என் அருகிலுள்ள வாங்குபவர்களைக் காட்டு”'],vph:['Type a command…','कमांड लिखें…','कमांड लिहा…','കമാൻഡ് ടൈപ്പ് ചെയ്യുക…','கட்டளையை தட்டச்சு செய்க…'],verr:['Voice unavailable. Type your command.','वॉइस उपलब्ध नहीं। कमांड लिखें।','व्हॉइस उपलब्ध नाही. कमांड लिहा.','വോയ്സ് ലഭ്യമല്ല. ടൈപ്പ് ചെയ്യുക.','குரல் இல்லை. தட்டச்சு செய்க.'],listen:['Listening…','सुन रहा हूँ…','ऐकत आहे…','കേൾക്കുന്നു…','கேட்கிறது…'],heard:['You said','आपने कहा','तुम्ही म्हणालात','നിങ്ങൾ പറഞ്ഞത്','நீங்கள் சொன்னது'],a_lang:['Language changed','भाषा बदली','भाषा बदलली','ഭാഷ മാറ്റി','மொழி மாற்றப்பட்டது'],a_msg:['Opening messages','संदेश खोल रहा हूँ','संदेश उघडत आहे','സന്ദേശങ്ങൾ തുറക്കുന്നു','செய்திகளைத் திறக்கிறது'],a_sell:['Listing ready. Add location and price, then publish.','लिस्टिंग तैयार। स्थान और कीमत जोड़ें, फिर प्रकाशित करें।','लिस्टिंग तयार. ठिकाण आणि किंमत भरा, मग प्रकाशित करा.','ലിസ്റ്റിംഗ് തയ്യാർ. സ്ഥലവും വിലയും ചേർത്ത് പ്രസിദ്ധീകരിക്കുക.','பட்டியல் தயார். இடம், விலை சேர்த்து வெளியிடுங்கள்.'],a_rent:['Searching rental equipment near you…','पास के किराए के उपकरण खोज रहा हूँ…','जवळची भाड्याची उपकरणे शोधत आहे…','അടുത്തുള്ള വാടക ഉപകരണങ്ങൾ തിരയുന്നു…','அருகிலுள்ள வாடகை உபகரணங்களைத் தேடுகிறது…'],a_buy:['Searching buyers near you…','पास के खरीदार खोज रहा हूँ…','जवळचे खरेदीदार शोधत आहे…','അടുത്തുള്ള വാങ്ങുന്നവരെ തിരയുന്നു…','அருகிலுள்ள வாங்குபவர்களைத் தேடுகிறது…']};
const t=k=>{const a=D[k];return a?(a[LI.indexOf(st.lang)]||a[0]):k};
const SEED=[
{id:1,c:1,ty:'sell',m:'rice',q:.8,p:2600,u:'t',d:12,lc:['p_kamptee','p_nagpur'],o:'Ramesh P.',v:1,r:4.6},{id:2,c:1,ty:'sell',m:'rice',q:.7,p:1300,u:'t',d:28,lc:['p_umred','p_nagpur'],o:'Sunita K.',v:0,r:4.2},{id:3,c:1,ty:'sell',m:'rice',q:.5,p:2000,u:'t',d:18,lc:['p_hingna','p_nagpur'],o:'Vilas D.',v:1,r:4.4},
{id:4,c:1,ty:'sell',m:'cotton',q:1.5,p:3200,u:'t',d:35,lc:['p_wardha'],o:'Anil M.',v:1,r:4.5},{id:5,c:1,ty:'sell',m:'coconut',q:3,p:900,u:'t',d:8,lc:['p_kochi','st1'],o:'Joseph T.',v:1,r:4.7},
{id:6,c:3,ty:'rent',m:'tractor',q:1,p:1000,u:'hr',d:9,lc:['p_nagpur'],o:'o_kis',v:1,r:4.8},{id:7,c:3,ty:'rent',m:'rotav',q:1,p:1300,u:'hr',d:15,lc:['p_hingna','p_nagpur'],o:'Prakash S.',v:0,r:4.3},
{id:8,c:4,ty:'service',m:'harv',q:1,p:2200,u:'acre',d:22,lc:['p_katol'],o:'o_agr',v:1,r:4.4},{id:9,c:5,ty:'sell',m:'comp',q:2,p:4500,u:'t',d:20,lc:['p_wardha'],o:'o_grn',v:1,r:4.6}];
const RQ=[{id:1,ty:'buy',m:'rice',q:2,km:30,dl:4,w:['w_bio','p_nagpur']},{id:2,ty:'buy',m:'cotton',q:3,km:50,dl:11,w:['w_comp','p_wardha']},{id:3,ty:'rent',m:'tractor',q:2,km:50,dl:2,w:['w_far']},{id:4,ty:'service',m:'harv',q:5,km:30,dl:7,w:['w_far']},{id:5,ty:'sell',m:'wheat',q:4,km:40,dl:1,w:['w_far']}];
const BUY=[['w_bio','p_nagpur',15],['w_comp','p_wardha',28],['w_bri','p_katol',42]],CC=[['p_kamptee',10],['p_wardha',30]];
/* BACKEND FEED: campaigns are published by authorised government admins via the backend/API, never from this site. Replace with fetch('/api/campaigns'). */
const GOV=[
{id:'g1',n:'PM-KISAN',by:'cen',ac:.1,url:'https://pmkisan.gov.in'},
{id:'g2',n:'Crop Residue Management Subsidy',by:'cen',st:['st3','st4','st5'],any:['a1','a2'],url:'https://agrimachinery.nic.in'},
{id:'g3',n:'SMAM Farm Mechanisation',by:'cen',any:['a2'],ac:.1,url:'https://agrimachinery.nic.in'},
{id:'g4',n:'PM-KUSUM Solar Pumps',by:'cen',any:['a3'],ac:.1,url:'https://pmkusum.mnre.gov.in'},
{id:'g5',n:'GOBARdhan Biogas',by:'cen',any:['a4','a1'],url:'https://gobardhan.co.in'},
{id:'g6',n:'Agriculture Infrastructure Fund',by:'cen',any:['a4'],url:'https://agriinfra.dac.gov.in'},
{id:'g7',n:'Stubble-to-Value Drive 2026',by:'sta',st:['st0','st1','st2'],any:['a1'],url:'https://www.myscheme.gov.in',demo:1}];
const E=['','🌾','🧺','🚜','🔧','♻️'],MS=['rice','wheat','cotton','coconut','tractor','rotav','harv','comp'],STS=['st0','st1','st2','st3','st4','st5','st6'],ROLES=['farmer','buyer','renter','service','business'],ACTS=['a1','a2','a3','a4'];
let st=L('c2v3')||{lang:'en',theme:'system',user:null,ls:SEED,rq:RQ,saved:[],chats:{},bk:[],log:[],resp:[],bt:[]};
const sv=()=>{try{localStorage.setItem('c2v3',JSON.stringify(st))}catch(e){}},lk=i=>st.ls.find(l=>l.id==i);
const ttl=l=>l.t||t('m_'+l.m)+(l.ty=='sell'?' — '+l.q+' '+t('u_t'):''),on=o=>String(o).startsWith('o_')?t(o):o,pl=l=>l.lc.map(k=>Object.hasOwn(D,k)?t(k):esc(k)).join(', '),pr=l=>'₹'+l.p.toLocaleString('en-IN')+'/'+t('u_'+l.u),tm=ts=>new Date(ts).toLocaleTimeString(LC[st.lang],{hour:'2-digit',minute:'2-digit'});
const mask=p=>'+91 '+p.slice(3,5)+'XXXXXX'+p.slice(-2),phOf=o=>'+919'+String(100000+[...o].reduce((a,c)=>a+c.charCodeAt(0),0)).padStart(9,'0');
let F={q:'',c:0,ty:'',s:'new'},w={s:0,ty:'sell',c:1,m:'rice',t:'',q:'',u:'t',p:'',lc:'',pin:'',im:'',ng:1},rt='buy',rf='',tp=0,V={},gv={st:'st0',ac:'',act:[],done:0},mf={b:1,s:1,e:1,v:1,c:1,r:50},ms=-1,tmpU=null,tmpC='';
function toast(m){const e=$('#ts');e.textContent=m;e.style.display='block';clearTimeout(toast.h);toast.h=setTimeout(()=>e.style.display='none',3200)}
function md(h){$('#md').innerHTML=`<div class="bx"><button class="x" onclick="cm()" aria-label="${t('cancel')}">✕</button>${h}</div>`;$('#md').hidden=false}const cm=()=>$('#md').hidden=true,go=h=>{location.hash=h},go2=h=>{cm();go(h)};
const emp=(m,b='')=>`<div class="emp"><div style="font-size:46px">🌾</div><p>${m}</p>${b}</div>`;
function ev(ic,k,a='',n=0){st.log.unshift({ic,k,a,ts:Date.now(),n,r:0});st.log.length=Math.min(st.log.length,60);sv();hdr();if(n)toast(ic+' '+t(k)+' '+a)}
function theme(){const h=document.documentElement;st.theme==='system'?h.removeAttribute('data-theme'):h.dataset.theme=st.theme}
function th(){st.theme={system:'light',light:'dark',dark:'system'}[st.theme];sv();theme();hdr()}
function setL(l){st.lang=l;sv();document.documentElement.lang=l;hdr();render()}
function hdr(){const n=[['market','market'],['sell','sell'],['rent','rent'],['req','reqs'],['gov','gov'],['map','map'],['chat','msgs'],['hist','hist'],['impact','impact']],u=st.log.filter(x=>x.n&&!x.r).length,nm=st.user?esc(st.user.n.split(' ')[0]):'';
$('#hd').innerHTML=`<a href="#home" class="lg">🌱 Crop2Value</a><nav class="dn">${n.map(([h,k])=>`<a href="#${h}">${t(k)}</a>`).join('')}</nav><span class="sp"></span><select onchange="setL(this.value)" aria-label="🌐" style="width:auto">${LI.map(k=>`<option value="${k}" ${k==st.lang?'selected':''}>🌐 ${N[k]}</option>`).join('')}</select><button onclick="th()" aria-label="Theme">${{system:'⚙️',light:'☀️',dark:'🌙'}[st.theme]}</button><button onclick="bell()" aria-label="🔔">🔔${u?`<b class="bd">${u}</b>`:''}</button><button class="pr" onclick="acc()">${st.user?'👤 '+nm:t('login')}</button>`;
$('#bn').innerHTML=[['home','🏠'],['market','🔎'],['sell','➕'],['map','🗺️'],['chat','💬']].map(([h,i])=>`<a href="#${h}"><span>${i}</span>${t(h=='chat'?'msgs':h)}</a>`).join('')+`<button onclick="acc()"><span>👤</span>${st.user?nm:t('login')}</button>`}
const lg=x=>`<div class="cd">${x.ic} ${t(x.k)} ${esc(x.a)}<br><span class="mu">${tm(x.ts)}</span></div>`;
function bell(){st.log.forEach(n=>n.r=1);sv();hdr();const a=st.log.filter(x=>x.n);md(`<h3>🔔</h3>${a.length?a.slice(0,20).map(lg).join(''):emp(t('none'))}`)}
V.hist=()=>`<h2>🕘 ${t('hist')}</h2>${st.log.length?st.log.map(lg).join(''):emp(t('none'))}`;
function acc(){const u=st.user;
if(u)return md(`<h3>${esc(u.n)}</h3><p class="mu">${esc(u.m)} · ${esc(u.e)}</p><p>${ROLES.map(r=>`<label class="ch"><input type="checkbox" style="width:auto;min-height:0" ${u.r.includes(r)?'checked':''} onchange="rl('${r}',this.checked)"> ${t('r_'+r)}</label>`).join('')}</p><div class="row lf"><button onclick="go2('gov')">🏛️ ${t('gov')}</button><button onclick="go2('hist')">🕘 ${t('hist')}</button><button onclick="lo()">${t('logout')}</button></div>`);
md(`<h3>${t('login')}</h3><form onsubmit="return su(event)"><div class="f2"><div class="w"><label class="fl" for="an">${t('name')}</label><input id="an" required minlength="2" maxlength="60" autocomplete="name"></div><div><label class="fl" for="am">${t('mob')}</label><input id="am" inputmode="numeric" maxlength="10" required></div><div><label class="fl" for="as">${t('state')}</label><select id="as">${STS.map(s=>`<option>${t(s)}</option>`).join('')}</select></div><div><label class="fl" for="av">${t('vil')}</label><input id="av" required maxlength="60"></div><div><label class="fl" for="ar">${t('iam')}</label><select id="ar">${ROLES.map(r=>`<option value="${r}">${t('r_'+r)}</option>`).join('')}</select></div></div><button class="pr big" style="width:100%;margin-top:20px">${t('login')}</button></form><button style="width:100%;margin-top:10px" onclick="demoLogin()">${t('dm')}: ${t('r_farmer')}</button>`)}
function su(e){e.preventDefault();const m=$('#am').value.trim();if(!/^[6-9]\d{9}$/.test(m)){toast(t('im'));return false}st.user={n:$('#an').value.trim(),ph:'+91'+m,m:mask('+91'+m),e:'',r:[$('#ar').value],pv:1};sv();cm();hdr();render();toast('✅ '+st.user.n);return false}
function demoLogin(){st.user={n:'Ramesh Patil',ph:'+919000000001',m:mask('+919000000001'),e:'demo@crop2value.example',r:['farmer'],pv:1};sv();cm();hdr();render()}
function rl(r,on){const a=st.user.r;st.user.r=on?[...new Set([...a,r])]:a.filter(x=>x!=r);sv()}function lo(){st.user=null;sv();cm();hdr();render()}
const vb=l=>(l.v?`<span class="bg">✓ ${t('ver')}</span>`:'')+(l.r?' ⭐'+l.r:'');
const cd=l=>`<a class="cd" href="#l/${l.id}"><div class="im">${l.im?`<img src="${l.im}" alt="" loading="lazy">`:E[l.c]}</div><h4>${esc(ttl(l))}</h4><p class="pr2">${pr(l)}</p><p class="mu">📍 ${dkm(l)} · ${pl(l)}</p><p>${vb(l)}</p></a>`;
V.home=()=>`<section class="hero"><div class="vis" aria-hidden="true"><span>👩‍🌾</span><span>🌾</span><i>➜</i><span>🚜</span><i>➜</i><span>🏭</span></div><h1>CROP2VALUE</h1><p class="tg">${t('tag')}</p><p class="mu sb">${t('sub')}</p><div class="row"><button class="pr big" onclick="go('sell')">➕ ${t('sell')}</button><button class="big" onclick="go('req/buy')">🤝 ${t('find')}</button><button class="big" onclick="go('rent')">🚜 ${t('rent')}</button><button class="big" style="background:var(--ac);border-color:var(--ac);color:#111" onclick="sheet(1)">🎙️ ${t('ask')}</button></div>
<form class="rw" onsubmit="event.preventDefault();go('market/'+encodeURIComponent($('#hq').value))"><input id="hq" placeholder="${t('ph')}" aria-label="${t('ph')}"><button class="pr">🔎 ${t('go')}</button><button type="button" onclick="geo()" aria-label="${t('near')}">📍</button></form><div>${['rice','tractor','coconut','comp','harv'].map(k=>`<a class="ch" href="#market/${encodeURIComponent(t('m_'+k))}">${t('m_'+k)}</a>`).join('')}</div></section>
<div class="g tl">${[1,2,3,4,5].map(i=>`<a class="cd" href="#market" onclick="F.c=${i};F.ty=''"><div>${E[i]}</div><b>${t('c'+i)}</b></a>`).join('')}</div>
<div class="g tl" style="margin-top:14px">${[['gov','🏛️'],['map','🗺️'],['hist','🕘'],['impact','♻️'],['req','📋']].map(([h,i])=>`<a class="cd" href="#${h}"><div>${i}</div><b>${t(h=='req'?'reqs':h)}</b></a>`).join('')}</div>
<h2>${t('feat')}</h2><div class="g">${st.ls.slice(0,4).map(cd).join('')}</div><p class="mu">⚠️ ${t('dm')} · ${t('ind')}</p>`;
function geo(){F.s='nrst';navigator.geolocation?navigator.geolocation.getCurrentPosition(()=>go('market'),()=>toast('📍 ✕'),{timeout:6000}):toast('📍 ✕')}
const tk=q=>q.toLowerCase().split(/\s+/).filter(x=>x&&!/^(buyers?|near|me|for|show|rent)$/.test(x)),hay=l=>(ttl(l)+' '+t('m_'+l.m)+' '+l.m+' '+l.lc.map(k=>Object.hasOwn(D,k)?t(k):k).join(' ')).toLowerCase();
const flt=()=>{const k=tk(F.q);return st.ls.filter(l=>(!F.ty||l.ty===F.ty)&&(!F.c||l.c==F.c)&&k.every(x=>hay(l).includes(x))).sort((a,b)=>F.s==='nrst'?a.d-b.d:F.s==='low'?a.p-b.p:F.s==='high'?b.p-a.p:b.id-a.id)};
const res=()=>{const r=flt();return r.length?`<div class="g">${r.map(cd).join('')}</div>`:emp(t('none'),`<button onclick="F={q:'',c:0,ty:'',s:'new'};render()">${t('clr')}</button> <button class="pr" onclick="go('sell')">${t('sell')}</button>`)},upd=()=>{$('#res').innerHTML=res()};
V.market=a=>{if(a)F.q=a;return`<h2>${t('market')}</h2><div class="rw fgrid"><input value="${esc(F.q)}" oninput="F.q=this.value;upd()" placeholder="${t('ph')}" aria-label="${t('ph')}"><select onchange="F.c=+this.value;upd()" aria-label="${t('cat')}"><option value="0">${t('all')}</option>${[1,2,3,4,5].map(i=>`<option value="${i}" ${F.c==i?'selected':''}>${t('c'+i)}</option>`).join('')}</select><select onchange="F.ty=this.value;upd()"><option value="">${t('all')}</option><option value="sell" ${F.ty=='sell'?'selected':''}>${t('tsell')}</option><option value="rent" ${F.ty=='rent'?'selected':''}>${t('rentt')}</option><option value="service" ${F.ty=='service'?'selected':''}>${t('c4')}</option></select><select onchange="F.s=this.value;upd()">${[['new','new'],['nrst','nrst'],['low','low'],['high','high']].map(([v,k])=>`<option value="${v}" ${F.s==v?'selected':''}>${t(k)}</option>`).join('')}</select></div><div id="res">${res()}</div>`};
/* calls: verified users only, after an accepted order/booking */
let canCall=i=>{const u=st.user,l=lk(i);if(!u||!l||l.o===u.n)return 0;return(st.chats[i]||[]).some(m=>m.st)||st.bk.some(b=>b.l==i&&b.s>=1)};
let callBtn=i=>`<button ${canCall(i)?'class="pr"':'style="opacity:.6"'} onclick="call(${i})">📞 ${t('call')}</button>`;
function openChat(i){go('chat/'+i)}function reportL(i){toast('🚩 ✓')}
function call(i){const l=lk(i);if(!canCall(i))return toast(!st.user?t('clog'):t('clock'));const p=phOf(l.o);md(`<h3>📞 ${esc(on(l.o))}</h3><p class="mu">${esc(ttl(l))}</p><p><b>${mask(p)}</b> <span class="bg">${t('dm')}</span></p><div class="row"><button class="pr big" onclick="ev('📞','e_call','${esc(on(l.o)).replace(/'/g,'')}');toast('📞 ${t('dm')}')">📞 ${t('cnow')}</button><button onclick="cm()">${t('cancel')}</button></div>`)}
V.rent=a=>{const k=tk(a||''),r=st.ls.filter(l=>l.ty==='rent'&&k.every(x=>hay(l).includes(x)));return`<h2>🚜 ${t('rent')}</h2>${r.length?`<div class="g">${r.map(cd).join('')}</div>`:emp(t('none'),`<button onclick="go('rent')">${t('showall')}</button>`)}<h3>${t('mybk')}</h3>${st.bk.length?st.bk.map(b=>`<div class="cd"><b>${esc(ttl(lk(b.l)||{m:'tractor',ty:'rent'}))}</b><p class="mu">${b.f} → ${b.to} · ${b.d} ${t('u_day')} · ₹${b.tot} + ${t('dep')} ₹${b.dep}</p><span class="bg">${t('b'+b.s)}</span> ${b.s==1?`<button class="pr" onclick="pay(${b.id})">${t('pay')}</button>`:''} ${callBtn(b.l)}</div>`).join(''):`<p class="mu">${t('none')}</p>`}`};
function pay(i){const b=st.bk.find(x=>x.id==i);b.s=2;sv();render();setTimeout(()=>{b.s=3;sv();ev('✅','e_ok',ttl(lk(b.l)),1);if(location.hash=='#rent')render()},1200)}
V.l=id=>{const l=lk(id);if(!l)return emp(t('none'),`<button onclick="go('market')">${t('market')}</button>`);const s=st.saved.includes(l.id),td=new Date().toISOString().slice(0,10);
return`<a class="bk" href="#market">←</a><div class="cd"><div class="im" style="height:160px">${l.im?`<img src="${l.im}" alt="">`:E[l.c]}</div><h2>${esc(ttl(l))}</h2><p class="pr2" style="font-size:24px">${pr(l)}</p><p class="mu">📍 ${t('apx')} ${dkm(l)} · ${pl(l)}<br>${t('priv')}</p><p>👤 ${esc(on(l.o))} ${vb(l)}</p>
<div class="row lf acts"><button onclick="openChat(${l.id})">💬 ${t('chat')}</button><button onclick="tg(${l.id})">${s?'❤️':'🤍'} ${t('save')}</button><button onclick="navigator.clipboard&&navigator.clipboard.writeText(location.href);toast('🔗 ✓')" aria-label="🔗">🔗</button><button onclick="reportL(${l.id})" aria-label="🚩">🚩</button></div>
${l.ty==='rent'?`<h3>${t('book')}</h3><div class="f2"><div><label class="fl" for="bf">${t('from')}</label><input type="date" id="bf" min="${td}" value="${td}"></div><div><label class="fl" for="bt">${t('to')}</label><input type="date" id="bt" min="${td}" value="${td}"></div></div><p class="mu">${t('dep')}: 20%</p><button class="pr big" onclick="bk(${l.id})">${t('book')}</button>`:`<h3>${t('offer')}</h3><div class="f2"><div><label class="fl" for="oq">${t('qty')}</label><input id="oq" type="number" step="0.1" min="0.1" value="${l.q}"></div><div><label class="fl" for="op">${t('price')} (₹)</label><input id="op" type="number" min="1" value="${l.p}"></div></div><button class="pr big" style="margin-top:14px" onclick="of(${l.id})">💰 ${t('offer')}</button>`}</div>
${l.ty==='sell'&&l.c==1?`<h3>🎯 ${t('match')} <span class="mu">(${t('ind')})</span></h3>${BUY.map(([n,p,d])=>`<div class="cd">🏭 ${t(n)} · ${t(p)} · ${d} ${t('km')} · <b>${Math.max(50,Math.round(100-d*1.2))}% ${t('mt')}</b></div>`).join('')}`:''}`};
function tg(i){const a=st.saved;a.includes(i)?a.splice(a.indexOf(i),1):a.push(i);sv();render()}
function bk(i){const l=lk(i),f1=$('#bf').value,t1=$('#bt').value;if(!st.user)return acc();if(t1<f1)return toast(t('dte'));if(st.bk.some(b=>b.l==i&&f1<=b.to&&t1>=b.f))return toast(t('nav'));
const d=Math.round((new Date(t1)-new Date(f1))/864e5)+1,hh=l.u=='hr'?Math.min(12,Math.max(1,+(($('#bh')||{}).value)||4)):1,b={id:Date.now(),l:i,f:f1,to:t1,d,tot:d*hh*l.p,dep:Math.round(hh*l.p*.2),s:0};st.bk.push(b);ev('📅','e_bk',ttl(l),1);go('rent');setTimeout(()=>{b.s=1;ev('✅','e_bka',on(l.o),1);if(location.hash=='#rent')render()},1800)}
function msg(i,o){(st.chats[i]=st.chats[i]||[]).push({ts:Date.now(),...o});sv()}
const rr=i=>{if(location.hash=='#chat/'+i)render()};
function reply(i,o,k){tp=i;rr(i);setTimeout(()=>{tp=0;msg(i,o);if(k)ev(k[0],k[1],k[2],1);rr(i)},1300)}
function of(i){if(!st.user)return acc();const l=lk(i),q=+$('#oq').value,p=+$('#op').value;if(!(q>0)||!(p>0))return toast(t('e_det'));msg(i,{w:'me',k:'off',q,p});ev('💰','e_off',ttl(l));go('chat/'+i);reply(i,{w:'th',k:'ctr',p:Math.round((p+l.p)/2)},['🔁','e_ctr',on(l.o)])}
function acp(i,x){const m=st.chats[i][x];m.st=1;msg(i,{w:'me',k:'accd',p:m.p});ev('✅','e_ok',ttl(lk(i)),1);rr(i)}
function snd(e,i){e.preventDefault();const v=$('#cx').value.trim();if(!v)return false;msg(i,{w:'me',x:v});reply(i,{w:'th',k:'thx'},['💬','e_msg',on(lk(i).o)]);render();return false}
const bub=(m,i,a)=>{const x=m.x?esc(m.x):m.k=='off'?`💰 ${t('offm')}: ${m.q} × ₹${m.p}`:m.k=='ctr'?`🔁 ${t('ctr')}: <b>₹${m.p}</b> ${m.st?'✅':`<button class="pr sm" onclick="acp(${a},${i})">✓ ${t('acc')}</button>`}`:m.k=='accd'?`✅ ${t('accd')} ₹${m.p}`:t('thx');return`<div class="mb ${m.w=='me'?'me':''}">${x}<small>${tm(m.ts)}${m.w=='me'?' ✓✓':''}</small></div>`};
V.chat=a=>{if(!a){const ids=Object.keys(st.chats).filter(i=>lk(i));return`<h2>${t('msgs')}</h2>`+(ids.length?ids.map(i=>{const l=lk(i),m=st.chats[i].at(-1);return`<a class="cd" href="#chat/${i}"><b>${esc(ttl(l))}</b><p class="mu">${m.x?esc(m.x):m.k?'💰 ₹'+(m.p||''):''}</p></a>`}).join(''):emp(t('none'),`<button class="pr" onclick="go('market')">${t('market')}</button>`))}
const l=lk(a);if(!l)return V.home();return`<a class="bk" href="#chat">←</a> <h3>${esc(ttl(l))} <span class="bg">🟢 ${t('onl')}</span></h3><div class="row lf acts"><button onclick="go('l/${a}')">💰 ${t('offer')}</button></div><div class="ct" aria-live="polite">${(st.chats[a]||[]).map((m,i)=>bub(m,i,a)).join('')}${tp==a?'<div class="mb dots"><i></i><i></i><i></i></div>':''}</div><form class="rw" onsubmit="return snd(event,${a})"><input id="cx" maxlength="300" required aria-label="${t('chat')}"><button class="pr" aria-label="${t('go')}">➤</button></form>`};
const agg=r=>{const c=st.ls.filter(l=>l.ty==='sell'&&l.m===r.m&&l.d!=null&&l.d<=r.km),tot=+c.reduce((a,l)=>a+l.q,0).toFixed(2);return{c,tot,ok:c.length>1&&tot>=r.q}};
function mkb(i){st.bt.push({r:i,s:0});sv();render()}function adv(i){const b=st.bt.find(x=>x.r==i);b.s=Math.min(5,b.s+1);sv();render()}function sp(i){st.resp.push(i);ev('📨','e_off','',1);render()}
const wh=q=>Array.isArray(q.w)?q.w.map(k=>Object.hasOwn(D,k)?t(k):k).join(', ')+' ✓':esc(q.w);
V.req=a=>{const[x,y]=(a||'').split('/');if(x)rt=x;rf=y||'';const k=tk(rf),r=st.rq.filter(q=>q.ty===rt&&k.every(z=>(t('m_'+q.m)+q.m).toLowerCase().includes(z)));
return`<h2>📋 ${t('reqs')}</h2><div class="row lf">${[['buy',t('buy')],['sell',t('tsell')],['rent',t('rentt')],['service',t('c4')]].map(([z,n])=>`<button class="ch ${rt==z?'on':''}" onclick="rt='${z}';rf='';render()">${n}</button>`).join('')}</div>${r.length?r.map(q=>{const g=agg(q),b=st.bt.find(z=>z.r==q.id);return`<div class="cd"><span class="bg">${{buy:t('buy'),sell:t('tsell'),rent:t('rentt'),service:t('c4')}[q.ty]}</span><h4>${t(q.ty=='sell'?'have':'need')}: ${t('m_'+q.m)} — ${q.q} ${t(q.ty=='rent'?'u_day':q.ty=='service'?'u_acre':'u_t')}</h4><p class="mu">📍 ≤${q.km} ${t('km')} · ⏳ ${q.dl} ${t('u_day')} · ${wh(q)}</p>${st.resp.includes(q.id)?`<span class="bg">✓ ${t('resp')}</span>`:`<button class="pr" onclick="sp(${q.id})">${q.ty=='buy'||q.ty=='sell'?t('supply'):t('provide')}</button>`}${q.ty=='buy'&&g.ok?`<div class="ag"><b>🤝 ${t('agg')}</b><br>${g.c.map(l=>`${esc(on(l.o))} ${l.q}${t('u_t')} (${l.d}${t('km')})`).join(' + ')} = <b>${g.tot} ${t('u_t')}</b> ≥ ${q.q}<br><span class="mu">${t('logi')} ≈ ₹${g.c.reduce((s,l)=>s+l.d,0)*20} (${t('ind')})</span><br>${b?`<span class="bg">${t('bs'+b.s)}</span> ${b.s<5?`<button class="sm" onclick="adv(${q.id})">${t('nxt')} →</button>`:''}`:`<button class="pr" onclick="mkb(${q.id})">${t('mk')}</button>`}</div>`:''}</div>`}).join(''):emp(t('none'),`<button onclick="rf='';render()">${t('showall')}</button> <button class="pr" onclick="w.ty='request';w.s=1;go('sell')">${t('post')}</button>`)}`};
const dkm=l=>l.d==null?'—':'~'+l.d+' '+t('km');
V.sell=()=>{const s=w.s,I=(k,lb,ty='text')=>`<label class="fl" for="w_${k}">${lb}</label><input id="w_${k}" ${ty=='number'?'type="number" min="0" step="any"':''} value="${esc(w[k])}" oninput="w.${k}=this.value">`,S=(k,lb,o)=>`<label class="fl" for="w_${k}">${lb}</label><select id="w_${k}" onchange="w.${k}=this.value">${o}</select>`;let h='';
if(s==0)h=`<h3>1/5 · ${t('w1')}</h3><div class="row">${[['sell',t('sell')],['rent',t('rent')],['service',t('c4')],['request',t('rqt')]].map(([k,n])=>`<button class="big ${w.ty==k?'pr':''}" onclick="w.ty='${k}';w.s=1;render()">${n}</button>`).join('')}</div>`;
if(s==1)h=`<h3>2/5 · ${t('cat')}</h3>${S('c',t('cat'),[1,2,3,4,5].map(i=>`<option value="${i}" ${w.c==i?'selected':''}>${E[i]} ${t('c'+i)}</option>`).join(''))}${S('m',t('mat'),MS.map(k=>`<option value="${k}" ${w.m==k?'selected':''}>${t('m_'+k)}</option>`).join(''))}`;
if(s==2)h=`<h3>3/5 · ${t('det')}</h3>${I('t',t('ttl'))}<div class="f2"><div>${I('q',t('qty'),'number')}</div><div>${S('u',t('unit'),['t','kg','day','acre'].map(u=>`<option value="${u}" ${w.u==u?'selected':''}>${t('u_'+u)}</option>`).join(''))}</div></div>${I('p',t('price')+' (₹)','number')}<label class="ch" style="margin-top:14px"><input type="checkbox" style="width:auto;min-height:0" ${w.ng?'checked':''} onchange="w.ng=this.checked"> ${t('neg')}</label>`;
if(s==3)h=`<h3>4/5 · ${t('loc')} + ${t('photo')}</h3>${I('lc',t('locph'))}${I('pin',t('pin'))}<p class="mu">🔒 ${t('priv')}</p><label class="fl" for="w_im">${t('photo')}</label><input id="w_im" type="file" accept="image/png,image/jpeg,image/webp" onchange="img(this)">${w.im?`<img src="${w.im}" alt="" style="height:90px;border-radius:12px;margin-top:10px">`:''}`;
if(s==4)h=`<h3>5/5 · ${t('prev')}</h3><div class="cd"><b>${esc(w.t||t('m_'+w.m))}</b><p class="pr2">₹${esc(w.p)}/${t('u_'+w.u)}</p><p class="mu">${esc(w.q)} ${t('u_'+w.u)} · ${t('m_'+w.m)} · 📍 ${esc(w.lc)}</p></div><button class="pr big" onclick="pubL()">${t('pub')}</button>`;
return`<h2>➕ ${t('sell')}</h2>${h}${s>0?`<div class="row"><button onclick="w.s--;render()">← ${t('back')}</button>${s<4?`<button class="pr" onclick="nx()">${t('next')} →</button>`:''}</div>`:''}`};
function img(e){const f1=e.files[0];if(!f1)return;if(!/^image\/(png|jpeg|webp)$/.test(f1.type)||f1.size>1.5e6)return toast('PNG/JPG/WebP ≤ 1.5 MB');const r=new FileReader();r.onload=()=>{w.im=r.result;render()};r.readAsDataURL(f1)}
function nx(){if(w.s==2&&(!(+w.q>0)||!(+w.p>0)))return toast(t('e_det'));if(w.s==3&&String(w.lc).trim().length<3)return toast(t('e_loc'));w.s++;render()}
function pubL(){if(!st.user)return acc();const c=w.ty=='rent'?3:w.ty=='service'?4:w.c;let l;
if(w.ty=='request'){st.rq.unshift({id:Date.now()%1e7,ty:'buy',m:w.m,q:+w.q,km:30,dl:7,w:st.user.n});rt='buy'}else{l={id:Date.now()%1e7,c,ty:w.ty=='rent'?'rent':w.ty=='service'?'service':'sell',m:w.m,t:w.t.trim(),q:+w.q,p:+w.p,u:w.u,d:3,lc:[w.lc],o:st.user.n,v:0,r:0,im:w.im&&w.im.startsWith('data:image/')?w.im:''};st.ls.unshift(l)}
ev('📢','e_pub',l?ttl(l):t('m_'+w.m),1);w={s:0,ty:'sell',c:1,m:'rice',t:'',q:'',u:'t',p:'',lc:'',pin:'',im:'',ng:1};go(l?'market':'req/buy')}
V.impact=()=>{const s=st.ls.filter(l=>l.ty=='sell'),tn=s.reduce((a,l)=>a+l.q,0).toFixed(1),fm=new Set(st.ls.map(l=>l.o)).size,dl=Object.values(st.chats).filter(c=>c.some(m=>m.st)).length;
return`<h2>♻️ ${t('impact')}</h2><p class="mu">${t('dm')} · ${t('ind')}</p><div class="st"><div class="cd"><b>${tn} ${t('u_t')}</b>🌾 ${t('i_res')}</div><div class="cd"><b>${(tn*.9).toFixed(1)} ${t('u_t')}</b>♻️ ${t('i_div')}</div><div class="cd"><b>${fm}</b>🤝 ${t('i_far')}</div><div class="cd"><b>${BUY.length}</b>🏭 ${t('i_buy')}</div><div class="cd"><b>${st.bk.length}</b>🚜 ${t('i_rent')}</div><div class="cd"><b>${dl}</b>📦 ${t('i_deal')}</div></div><h3>${t('i_chart')}</h3><div class="bar" role="img" aria-label="${t('i_chart')}">${[30,45,60,52,80,95].map(v=>`<i style="height:${v}%"></i>`).join('')}</div>`};
/* government schemes: apply opens the official portal in a new tab */
const match=(s,u)=>(!s.st||s.st.includes(u.st))&&(!s.any||s.any.some(a=>u.act.includes(a)))&&u.ac>=(s.ac||0);
const crit=s=>['📍 '+(s.st?s.st.map(t).join(', '):'🇮🇳'),s.any?'🎯 '+s.any.map(t).join(' / '):'',s.ac?'🌱 ≥ '+s.ac+' '+t('u_acre'):''].filter(Boolean).join(' · ');
const gc=(s,e)=>`<div class="cd gc ${e?'ok':''}"><b>${esc(s.n)}</b> ${s.demo?`<span class="bg">${t('dm')}</span>`:''} ${e?`<span class="bg">✓ ${t('mayel')}</span>`:''}<p class="mu">🏛️ ${t(s.by)}</p><p class="pr2">${Object.hasOwn(D,s.id+'b')?t(s.id+'b'):esc((s.b&&(s.b[st.lang]||s.b.en))||'')}</p><p class="mu">${crit(s)}</p><a class="pr" href="${esc(s.url)}" data-n="${esc(s.n)}" target="_blank" rel="noopener noreferrer" onclick="ev('🏛️','e_app',this.dataset.n)">${t('apply')}</a></div>`;
V.gov=()=>{const rs=gv.done?GOV.filter(s=>match(s,gv)):[];
return`<h2>🏛️ ${t('gov')}</h2><p class="mu">${t('gnote')}</p><form class="cd" onsubmit="return chk(event)"><h3 style="margin-top:0">${t('elig')}</h3><div class="f2"><div><label class="fl" for="gs">${t('state')}</label><select id="gs">${STS.map(s=>`<option value="${s}" ${gv.st==s?'selected':''}>${t(s)}</option>`).join('')}</select></div><div><label class="fl" for="ga">${t('land')}</label><input id="ga" type="number" min="0" step="0.1" required value="${esc(gv.ac)}"></div><div class="w"><label class="fl">${t('what')}</label>${ACTS.map(k=>`<label class="ch"><input type="checkbox" class="gk" value="${k}" style="width:auto;min-height:0" ${gv.act.includes(k)?'checked':''}> ${t(k)}</label>`).join('')}</div></div><button class="pr big" style="width:100%;margin-top:18px">${t('elig')}</button></form>${gv.done?`<h3>✅ ${rs.length} ${t('sug')}</h3>${rs.length?rs.map(s=>gc(s,1)).join(''):emp(t('nom'))}`:''}<h3>${t('actv')}</h3>${GOV.filter(s=>!gv.done||!match(s,gv)).map(s=>gc(s,0)).join('')}`};
function chk(e){e.preventDefault();const a=[...document.querySelectorAll('.gk:checked')].map(x=>x.value);if(!a.length){toast(t('what'));return false}gv={st:$('#gs').value,ac:+$('#ga').value,act:a,done:1};render();return false}
/* map: schematic radar view with approximate positions (swap for Leaflet + OpenStreetMap tiles in the deployed zip, see README) */
const mpts=()=>{const a=[];st.ls.forEach(l=>{const g=l.ty=='sell'?'s':l.ty=='rent'?'e':'v';a.push({k:g,ic:{s:'🌾',e:'🚜',v:'🔧'}[g],n:ttl(l),d:l.d,go:'l/'+l.id})});BUY.forEach(([n,p,d])=>a.push({k:'b',ic:'🏭',n:t(n)+' · '+t(p),d,go:'req/buy'}));CC.forEach(([p,d])=>a.push({k:'c',ic:'📦',n:t('cc')+' · '+t(p),d,go:'req/buy'}));a.forEach((x,i)=>x.i=i);return a.filter(x=>mf[x.k]&&x.d!=null&&x.d<=mf.r)};
V.map=()=>{const P=mpts(),R=150,C=170,S=P.find(x=>x.i==ms),pos=x=>{const a=(x.i*137.5+20)*Math.PI/180,r=R*Math.sqrt(x.d/50);return[C+r*Math.cos(a),C+r*Math.sin(a)]};
return`<h2>🗺️ ${t('map')}</h2><div class="row lf">${[['b',t('f_b')],['s',t('f_s')],['e',t('c3')],['v',t('c4')],['c',t('cc')]].map(([k,n])=>`<button class="ch ${mf[k]?'on':''}" onclick="mf['${k}']=!mf['${k}'];render()">${n}</button>`).join('')}</div><div class="row lf">${[5,10,25,50].map(r=>`<button class="ch ${mf.r==r?'on':''}" onclick="mf.r=${r};render()">${r} ${t('km')}</button>`).join('')}</div>
<div class="cd mapw"><svg viewBox="0 0 340 340" role="img" aria-label="${t('map')}">${[5,10,25,50].map(d=>`<circle cx="170" cy="170" r="${R*Math.sqrt(d/50)}" class="rg"/><text x="170" y="${170-R*Math.sqrt(d/50)-3}" class="rl" text-anchor="middle">${d} ${t('km')}</text>`).join('')}<g class="sweep"><path d="M170 170 L170 20 A150 150 0 0 1 240 37 Z"/></g><text x="170" y="178" text-anchor="middle" font-size="22">📍</text>${P.map(x=>{const[X,Y]=pos(x);return`<g class="mkr" tabindex="0" role="button" aria-label="${esc(x.n)}" onclick="ms=${x.i};render()" onkeydown="if(event.key==='Enter'){ms=${x.i};render()}"><circle cx="${X}" cy="${Y}" r="14" class="pu"/><text x="${X}" y="${Y+6}" text-anchor="middle" font-size="18">${x.ic}</text></g>`}).join('')}</svg></div>${P.length?'':emp(t('none'))}${S?`<div class="cd">${S.ic} <b>${esc(S.n)}</b><p class="mu">~${S.d} ${t('km')} · ${t('apx')}</p><button class="pr" onclick="go('${S.go}')">${t('open')}</button></div>`:''}<p class="mu">🔒 ${t('mapn')} 📍 = ${t('you')}</p>`};
/* voice + assistant */
const MT=[['wheat',/wheat|गेहूं|गहू|ഗോതമ്പ്|கோதுமை/],['cotton',/cotton|कपास|कापूस|പരുത്തി|பருத்தி/],['coconut',/coconut|नारियल|नारळ|തേങ്ങ|தேங்காய்/],['rice',/rice|straw|paddy|तांदळ|तांदूळ|चावल|धान|पराली|നെല്|நெல்|வைக்கோல்/]],WN={one:1,two:2,three:3,four:4,five:5,'एक':1,'दो':2,'दोन':2,'तीन':3};
const mat=s=>(MT.find(([n,r])=>r.test(s))||[])[0]||'',qn=s=>{const m=s.match(/(\d+(?:\.\d+)?|one|two|three|four|five|एक|दो|दोन|तीन)\s*(?:ton|tonne|tonnes|tons|टन|ടൺ|டன்)/);return m?+(WN[m[1]]||m[1]):0},say=m=>{const e=$('#vs');if(e)e.textContent=m};
function sheet(a){$('#sh').hidden=false;$('#sh').innerHTML=`<div class="bx"><button class="x" onclick="$('#sh').hidden=true" aria-label="${t('cancel')}">✕</button><h3>✨ ${t('ask')}</h3><button id="mb" class="pr big" style="width:100%" onclick="lis()">🎙️ ${N[st.lang]}</button><p id="vs" class="mu" aria-live="polite">${t('try')}</p><form class="rw" onsubmit="event.preventDefault();run($('#vt').value)"><input id="vt" placeholder="${t('vph')}" required aria-label="${t('vph')}"><button class="pr" aria-label="${t('go')}">➤</button></form></div>`;if(a)lis()}
function lis(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return say(t('verr'));try{const r=new R();r.lang=LC[st.lang];r.onstart=()=>{$('#mb').classList.add('on');say(t('listen'))};r.onresult=e=>run(e.results[0][0].transcript);r.onerror=()=>say(t('verr'));r.onend=()=>$('#mb')?.classList.remove('on');r.start()}catch(e){say(t('verr'))}}
function run(x){const s=x.toLowerCase(),m=mat(s),q=qn(s),lgs={english:'en','हिन्दी':'hi','हिंदी':'hi',hindi:'hi','मराठी':'mr',marathi:'mr','മലയാളം':'ml',malayalam:'ml','தமிழ்':'ta',tamil:'ta'},L1=Object.keys(lgs).find(k=>s.includes(k));let o;ev('🎙️','e_vo',x);
if(L1&&/language|भाषा|भाषेत|ഭാഷ|மொழி/.test(s)){setL(lgs[L1]);o=t('a_lang')}
else if(/message|chat|संदेश|मैसेज|സന്ദേശ|செய்தி/.test(s)){go('chat');o=t('a_msg')}
else if(/scheme|yojana|योजना|പദ്ധതി|திட்ட/.test(s)){go('gov');o=t('gov')}
else if(/\bmap\b|नक्शा|नकाशा|മാപ്പ്|வரைபடம்/.test(s)){go('map');o=t('map')}
else if(/history|इतिहास|ചരിത്രം|வரலாறு/.test(s)){go('hist');o=t('hist')}
else if(/create|listing|\bsell\b|बेच|विक|लिस्ट|ലിസ്റ്റ്|വിൽ|பட்டியல்|விற்/.test(s)){w={...w,ty:'sell',c:1,m:m||'rice',q:q||'',t:'',s:m?2:1};go('sell');o=(m?t('m_'+m)+' ':'')+(q?q+' '+t('u_t')+'. ':'')+t('a_sell')}
else if(/rent|tractor|equipment|किराए|भाड्य|उपकरण|ട്രാക്ടർ|ഉപകരണ|വാടക|டிராக்டர்|உபகரண|வாடகை|ट्र[ैॅ]क्टर/.test(s)){go('rent/'+(/tractor|ट्र[ैॅ]क्टर|ട്രാക്ടർ|டிராக்டர்/.test(s)?encodeURIComponent(t('m_tractor').split(' ').pop()):''));o=t('a_rent')}
else if(/buyer|खरीदार|खरेदीदार|വാങ്ങുന്ന|வாங்குபவ/.test(s)){rt='buy';go('req/buy/'+encodeURIComponent(m?t('m_'+m):''));o=t('a_buy')}
else{go('market/'+encodeURIComponent(m?t('m_'+m):x));o=t('go')+'…'}
say(t('heard')+': “'+x+'” → '+o);try{const u=new SpeechSynthesisUtterance(o);u.lang=LC[st.lang];speechSynthesis.speak(u)}catch(e){}}
function dec(){const h=location.hash||'#home',a=$('#app'),v=h.slice(1).split('/')[0];document.querySelectorAll('.dn a').forEach(x=>x.classList.toggle('on',x.getAttribute('href')=='#'+v));a.classList.toggle('wiz',v=='sell');
if(v=='sell')a.insertAdjacentHTML('afterbegin',`<div class="pb"><i style="width:${(w.s+1)*20}%"></i></div>`);
if(v=='chat'||v=='l'){const id=h.split('/')[1],r=a.querySelector('.row');if(id&&r)r.insertAdjacentHTML('beforeend',callBtn(id))}
if(v=='impact'||v=='home')a.querySelectorAll('.st b').forEach(b=>{const m=b.textContent.match(/^([\d.]+)(.*)$/);if(!m)return;const n=+m[1],d=m[1].includes('.')?1:0,s0=performance.now();(function f2(x){const p=Math.min(1,(x-s0)/900);b.textContent=(n*p).toFixed(d)+m[2];if(p<1)requestAnimationFrame(f2)})(s0)})}
function render(){try{const[v,...r]=decodeURIComponent(location.hash.slice(1)||'home').split('/');$('#app').innerHTML=(V[v]||V.home)(r.join('/'));dec()}catch(e){$('#app').innerHTML=emp('⚠️','<button class="pr" onclick="render()">↻</button>')}}
addEventListener('hashchange',()=>{cm();render();scrollTo(0,0)});theme();document.documentElement.lang=st.lang;hdr();setTimeout(render,250);
if('serviceWorker'in navigator&&/^https?:/.test(location.protocol))navigator.serviceWorker.register('sw.js').catch(()=>{});
Object.assign(D,{how:['How it works','यह कैसे काम करता है','हे कसे चालते','ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു','இது எப்படி வேலை செய்கிறது'],hw1:['List your material','अपनी सामग्री लिस्ट करें','तुमचे साहित्य लिस्ट करा','നിങ്ങളുടെ വസ്തു ലിസ്റ്റ് ചെയ്യുക','உங்கள் பொருளைப் பட்டியலிடுங்கள்'],hw2:['Find the right buyer','सही खरीदार खोजें','योग्य खरेदीदार शोधा','ശരിയായ വാങ്ങുന്നയാളെ കണ്ടെത്തുക','சரியான வாங்குபவரைக் கண்டறியுங்கள்'],hw3:['Connect & negotiate','जुड़ें और मोलभाव करें','संपर्क करा आणि वाटाघाटी करा','ബന്ധപ്പെട്ട് വിലപേശുക','தொடர்பு கொண்டு பேசுங்கள்'],hw4:['Pickup / delivery','पिकअप / डिलीवरी','पिकअप / डिलिव्हरी','പിക്കപ്പ് / ഡെലിവറി','பிக்கப் / டெலிவரி'],hw5:['Get paid','भुगतान पाएं','पैसे मिळवा','പണം നേടുക','பணம் பெறுங்கள்']});
const SCENE=`<svg class="scene" viewBox="0 0 600 190" aria-hidden="true"><defs><linearGradient id="sg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#a8daff"/><stop offset="1" stop-color="#fff1c9"/></linearGradient></defs><rect width="600" height="190" fill="url(#sg)"/><g class="sun"><circle cx="500" cy="48" r="26" fill="#ffc83d"/></g><path d="M0 118Q150 68 300 112T600 98V190H0Z" fill="#8bcf7f"/><path d="M0 146Q200 110 380 142T600 130V190H0Z" fill="#4caf50"/><path d="M0 172H600" stroke="#2e7d32" stroke-width="8" stroke-dasharray="6 10" opacity=".5"/><text x="34" y="150" font-size="38">👩‍🌾</text><text x="88" y="152" font-size="26">🌾</text><text x="300" y="150" font-size="26">🌾</text><text x="474" y="140" font-size="46">🏭</text><circle class="smk" cx="500" cy="88" r="7" fill="#fff"/><circle class="smk" cx="508" cy="80" r="5" fill="#fff"/><g class="trk"><rect x="100" y="132" width="52" height="20" rx="5" fill="#d84315"/><rect x="126" y="114" width="24" height="22" rx="4" fill="#ef6c00"/><g transform="translate(112 156)"><g class="whl"><circle r="14" fill="#263238"/><path d="M-14 0H14M0-14V14" stroke="#607d8b" stroke-width="2"/><circle r="4" fill="#ffc83d"/></g></g><circle cx="146" cy="160" r="9" fill="#263238"/></g></svg>`;
const _home=V.home;
V.home=a=>{const s=st.ls.filter(l=>l.ty=='sell'),tn=s.reduce((x,l)=>x+l.q,0).toFixed(1),fm=new Set(st.ls.map(l=>l.o)).size,strip=`<div class="st strip"><div class="cd"><b>${tn} ${t('u_t')}</b>🌾 ${t('i_res')}</div><div class="cd"><b>${fm}</b>🤝 ${t('i_far')}</div><div class="cd"><b>${BUY.length}</b>🏭 ${t('i_buy')}</div></div><h2>${t('how')}</h2><div class="how">${[['📦','hw1'],['🔎','hw2'],['💬','hw3'],['🚚','hw4'],['💰','hw5']].map(([i,k])=>`<div class="cd"><div>${i}</div>${t(k)}</div>`).join('')}</div>`;
 return _home(a).replace(/<div class="vis"[\s\S]*?<\/div>/,'').replace('</section>',()=>LEAVES+SCENE+'</section>'+TICK()).replace('<p class="mu">⚠️',()=>strip+'<p class="mu">⚠️')+`<footer class="ft"><b>🌱 Crop2Value</b><span>${t('tag')}</span></footer>`};
/* ===== v4: price benchmarks, tidy layout helpers, card animations ===== */
Object.assign(D,{u_hr:['hour','घंटा','तास','മണിക്കൂർ','மணி'],rng:['Typical market range','सामान्य बाज़ार दर','सामान्य बाजारभाव','സാധാരണ വിപണി വില','வழக்கமான சந்தை விலை'],blw:['Below range','सीमा से कम','मर्यादेपेक्षा कमी','പരിധിക്ക് താഴെ','வரம்புக்குக் கீழே'],inr:['Within range','सीमा के भीतर','मर्यादेत','പരിധിക്കുള്ളിൽ','வரம்புக்குள்'],abv:['Above range','सीमा से अधिक','मर्यादेपेक्षा जास्त','പരിധിക്ക് മുകളിൽ','வரம்புக்கு மேலே'],nobm:['No reliable benchmark yet','अभी कोई भरोसेमंद मानक नहीं','अजून विश्वासार्ह मानक नाही','വിശ്വസനീയ മാനദണ്ഡം ഇതുവരെയില്ല','நம்பகமான அளவுகோல் இன்னும் இல்லை']});
/* Indicative ranges, Sept 2026 (sources in README > Price data). Missing key = no reliable public benchmark found. */
const MR={rice:[1200,3000,'t'],cotton:[3000,3500,'t'],comp:[3000,6000,'t'],tractor:[800,1500,'hr'],rotav:[800,1500,'hr'],harv:[1800,2900,'acre']},fmt=n=>n.toLocaleString('en-IN');
const rngHtml=l=>{const r=MR[l.m];if(!r)return`<p class="mu">📊 ${t('nobm')}</p>`;const[lo,hi,u]=r;if(l.u!=u)return'';const k=l.p<lo?'blw':l.p>hi?'abv':'inr',p=l.p<lo?0:l.p>hi?100:Math.round((l.p-lo)/(hi-lo)*100);return`<div class="rng"><b>📊 ${t('rng')}: ₹${fmt(lo)}–${fmt(hi)}/${t('u_'+u)}</b> <span class="bg ${k}">${t(k)}</span><div class="rbar"><i style="--p:${p}%"></i></div><p class="mu">${t('ind')} · Sep 2026</p></div>`};
const _L=V.l;V.l=id=>{const l=lk(id),h=_L(id);if(!l)return h;let o=h.replace('<div class="row lf acts">',rngHtml(l)+'<div class="row lf acts">');if(l.u=='hr')o=o.replace(/<p class="mu">[^<]*20%<\/p>/,`<div class="f2"><div><label class="fl" for="bh">${t('u_hr')}/${t('u_day')}</label><input id="bh" type="number" min="1" max="12" value="4"></div></div>`);return o};
const _S=V.sell;V.sell=()=>{let h=_S();if(w.s==2){const r=MR[w.m];h=h.replace('<label class="ch" style="margin-top:14px">',`<p class="mu">${r&&r[2]==w.u?`📊 ${t('rng')}: ₹${fmt(r[0])}–${fmt(r[1])}/${t('u_'+r[2])}`:`📊 ${t('nobm')}`}</p><label class="ch" style="margin-top:14px">`).replace('onchange="w.u=this.value"','onchange="w.u=this.value;render()"').replace(/(<option value="acre"[^>]*>[^<]*<\/option>)/,`$1<option value="hr"${w.u=='hr'?' selected':''}>${t('u_hr')}</option>`)}return h};
const LEAVES=[8,22,38,55,70,86].map((x,i)=>`<span class="leaf" style="left:${x}%;animation-delay:-${i*1.6}s;animation-duration:${8+i}s">🍃</span>`).join('');
const TICK=()=>{const it=['rice','cotton','comp','tractor','harv'].map(k=>{const[a,b,u]=MR[k];return`<span>🌾 ${t('m_'+k)} <b>₹${fmt(a)}–${fmt(b)}/${t('u_'+u)}</b></span>`}).join('');return`<div class="tick"><em>📊 ${t('rng')} · ${t('ind')}</em><div><div class="tk">${it}${it}</div></div></div>`};
const _dec=dec;dec=function(){_dec();fx()};
function fx(){const io=fx.io||(fx.io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const el=e.target;el.classList.add('in');fx.io.unobserve(el);setTimeout(()=>el.classList.remove('rv','in'),1100)}}),{threshold:.06})),v=location.hash.slice(1).split('/')[0]||'home';
 document.querySelectorAll('#app .g>*,#app .how>*,#app .st>*,#app .ag,#app .rng').forEach((el,i)=>{el.classList.add('rv');el.style.setProperty('--i',i%8);io.observe(el)});
 document.querySelectorAll('#bn a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+v))}
document.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const c=e.target.closest&&e.target.closest('.g>.cd');if(!c||c.classList.contains('rv'))return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(800px) rotateY(${x*7}deg) rotateX(${-y*7}deg) translateY(-5px)`});
document.addEventListener('mouseout',e=>{const c=e.target.closest&&e.target.closest('.g>.cd');if(c&&!c.contains(e.relatedTarget))c.style.transform=''});
document.addEventListener('pointerdown',e=>{const b=e.target.closest&&e.target.closest('button,a.pr');if(!b||b.id=='mic')return;const r=b.getBoundingClientRect(),d=Math.max(r.width,r.height),s=document.createElement('span');s.className='rp';s.style.cssText=`width:${d}px;height:${d}px;left:${e.clientX-r.left-d/2}px;top:${e.clientY-r.top-d/2}px`;b.appendChild(s);setTimeout(()=>s.remove(),600)});
setTimeout(fx,270);
